sudo: required
language: generic
services:
    - docker

before_install:
    - docker build -t alexmocanu/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true alexmocanu/docker-react npm run test
